parameters:
services:
  _defaults:
    autowire: true
    autoconfigure: true
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Migrations/'
      - '../src/Kernel.php'
  App\Game\Infrastructure\HttpClient\TwitchClient:
    arguments:
      $clientId: '%env(CLIENT_ID)%'
      $clientSecret: '%env(CLIENT_SECRET)%'

  App\Game\Infrastructure\HttpClient\IGDBClient:
    arguments:
      $clientId: '%env(CLIENT_ID)%'
