framework:
  messenger:
    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        serializer: messenger.transport.symfony_serializer
        options:
          exchange:
            name: game_offsets
    routing:
      'App\Application\CLI\Message\FetchGamesMessage': async
